/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asmcf17.app;

import java.util.Arrays;
import java.util.concurrent.CompletableFuture;

public class App {
    public static void main(String[] args) {
        System.out.println("MAIN");
        Simple simple = new Simple();
        simple.setField("value");
        CompletableFuture<Simple> simpleCf = new CompletableFuture();
        Arrays.stream(CompletableFuture.class.getDeclaredFields()).forEach((field -> System.out.println(field.getName())));
    }
}

