/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asmcf17;

import org.objectweb.asm.ClassReader;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        ClassPrinter printer = new ClassPrinter();
        ClassReader reader = new ClassReader("java.lang.Runnable");
        reader.accept(printer, 0);
    }
}

