/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asmcf17;

import asmcf17.app.App;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
